### ISSUE TITLE
timezone request parameter

### ISSUE THREAD

**Issue by apadmarao** [api-ai/apiai-java-sdk#11]
It looks as though the timezone request param is always set to the calendar default timezone. See [https://github.com/api-ai/apiai-java-sdk/blob/5d3708a7137279ae824d2b83a195000ecf42af14/libai/src/main/java/ai/api/AIDataService.java#L165](code).

To support users in different timezones, shouldn't the developer to override the default timezone and instead specify a different timezone per user?

**Comment by folomeev** [comment]
Thank you!

**Comment by apadmarao** [comment]
Thanks for fixing! Would appreciate a release as soon as you can.

**Comment by folomeev** [comment]
@apadmarao 
Fixed library v1.4.6 released
