### ISSUE TITLE
How to set sessionId?

### ISSUE THREAD

**Issue by IonutCiuta** [api-ai/apiai-java-sdk#15]
Hi,

Is there any way to set **sessionId** for a request?
For some reason, using the setter is not enough as somewhere along the way it get overriden.
I also looked into the configuration class and I don't see any point in which the sessionId is updated.

**Comment by folomeev** [comment]
Session Id is a part of `AIServiceContext` interface. You may create your of implementation or use `AIServiceContextBuilder` class methods.

Also you have several ways to pass service context with required session id value into the request:
1. As a constructor parameter when create `AIDataService`. In this case the given context will be assumed as a default one for each request invoked with this data service.
2. As a `AIDataService#request` method parameter. In this case the given context will be used to make a request and a default context will be ignored.

If you have any extra questions or would like to see a sample code please fill free to ask it here.

**Comment by IonutCiuta** [comment]
Thanks a lot! This solved my issue.

I haven't stumbled upon this `AIServiceContext ` in my search. I thought it would be something straight forward like in the NodeJS SDK.
