### ISSUE TITLE
Session ID is missing

### ISSUE THREAD

**Issue by Aselahp** [api-ai/apiai-java-sdk#3]
The query response does not contain the session ID. I dont see any session ID parameter in AIResponse object.Can you fix that? Thanks in advance.

**Comment by folomeev** [comment]
Yes, all missing fields going to be added in closest future.
Thank you for your report!

**Comment by folomeev** [comment]
Committed changes. Session ID is available via AiResponse.getSessionId() method.

**Comment by Aselahp** [comment]
Thnx
