### ISSUE TITLE
class path for running text example

### ISSUE THREAD

**Issue by ndpmurphy** [api-ai/apiai-java-sdk#4]
I have struggled for several hours now to get the text example to run. No matter what I do with the class path, I can not get it to find the classes required. Would it be possible to add a couple of lines to say how it is normally run e.g. is the library built and installed, or should the example point at it in its target dirctory. I am not sure whether there is a mistake in one of the pom.xml fles or maybe the build sequence I am using is not matching the authors expectation. It is also not clear to me if I need the library signed if I am just running this on  my local machine.

**Comment by a23sokolov** [comment]
We update Readme. We hope that instruction will help you.
