### ISSUE TITLE
While making a request its not taking user supplied sessionId.

### ISSUE THREAD

**Issue by anshchauhan** [api-ai/apiai-java-sdk#7]
Hi,
I'm making a request to api.ai as 
`AIRequest request = new AIRequest(line);
			request.setSessionId(uId);
			AIResponse response = dataService.request(request);`

but the request is not using the sessionId passed in AIRequest and its using the sessionId from the serviceContext which is sending same sessionId each time and its causing my contexts to be shared globally by all users. Do I need to create a new AIDataService object for each request and then set context?

**Comment by folomeev** [comment]
Hello!

Session Id is supposed to be a property of AIServiceContext which instance is aggregated by AIDataService. So it should normal to have one AIDataService instance per each session.

By the way, there is no setSessionId(String) method in AIRequest. How did you managed to compile the given code? Which version of library do you use? Or maybe you have modified the class code?

If you have any ideas or suggestions please fell free to share!

**Comment by anshchauhan** [comment]
I think in applications like android it's good to have one AIDataService for all the requests since every parameter including AIServiceContext will be same for each user.

But since server side will have concurrent requests from multiple users we'll either need one AIDataService which can take sessionId dynamically for each request or we save AIDataService object for each sessionId in memory which doesn't make much sense because AIDataService doesn't have much user specific data other than sessionId.

So for example in Spring I would like to autowire AIDataService so that it handles all kinds of requests.

P.S: AIRequest dsn't have any method setSessionId but its extending QuestionMetaData which has one. Infact its overriding my sessionId using the same method when I call dataService.request(request)

**Comment by snirmar** [comment]
Hello,
you wrote "By the way, there is no setSessionId(String) method in AIRequest. How did you managed to compile the given code? Which version of library do you use? Or maybe you have modified the class code?", but there is a method setSessionId in AIRequest. what it use for?

in addition, what is the best way to continue session after request? to implement AIServiceContext?

**Comment by folomeev** [comment]
Here is a suggestion: 
```java
// Create data service instance
AIDataService dataService = new AIDataService(config);

// Create some custom service context 
// It is possible to use AIServiceContextBuilder or 
// create any other AIServiceContext interface implementation 
AIServiceContext customContext = AIServiceContextBuilder.buildFromSessionId("customSessionId");

// Initialize some request data
AIRequest request = new AIRequest();

// Make a request with custom context
dataService.request(request, customContext);
```

Custom context support is already available in master branch.

**Comment by anshchauhan** [comment]
Yup just saw it. Thanks for the fix. I'll use it when its released.

**Comment by suresh777** [comment]
i tried same code but if i try to retrieve value in nodejs , i am not getting . var sessionId = request.body.sessionId
