### ISSUE TITLE
Support for getting current user contexts?

### ISSUE THREAD

**Issue by anshchauhan** [api-ai/apiai-java-sdk#8]
Hi,
Do you have any support for /contexts endpoint?
I wanted to get current user contexts as mentioned here:
https://docs.api.ai/docs/contexts#context-object

**Comment by folomeev** [comment]
Added new methods into AIDataService class:
- getActiveContexts
- getActiveContext
- addActiveContext
- addActiveContext
- resetActiveContexts
- removeActiveContext

The changes are available in the master branch and would be available in the maven repository in a next release.

**Comment by folomeev** [comment]
Now available in 1.3.4 release
