### ISSUE TITLE
Program Args

### ISSUE THREAD

**Issue by laine4466** [api-ai/apiai-java-sdk#9]
Hello! How do you program arguments in Intellij (Windows)? I am unable to find it in Run/Debug config. Any help is appreciated.

**Comment by xVir** [comment]
Hi, @laine4466 
Please import modules from folder `examples` using Project Structure dialog:

![screen 2017-01-16 16 12 23](https://cloud.githubusercontent.com/assets/278221/21976992/e0cbd3a0-dc06-11e6-8e4c-7e2035c05742.png)

![screen 2017-01-16 16 12 42](https://cloud.githubusercontent.com/assets/278221/21976994/e5c6059c-dc06-11e6-9b22-d7561f55ceab.png)

Thanks!
